from .clip_fallback import NODE_CLASS_MAPPINGS as CLIP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY
from .vae_fallback import NODE_CLASS_MAPPINGS as VAE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VAE_DISPLAY
from .is_anima_model import NODE_CLASS_MAPPINGS as ANIMA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ANIMA_DISPLAY
from .multi_image_preview import NODE_CLASS_MAPPINGS as MULTI_IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTI_IMAGE_DISPLAY

NODE_CLASS_MAPPINGS = {**CLIP_MAPPINGS, **VAE_MAPPINGS, **ANIMA_MAPPINGS, **MULTI_IMAGE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CLIP_DISPLAY, **VAE_DISPLAY, **ANIMA_DISPLAY, **MULTI_IMAGE_DISPLAY}

WEB_DIRECTORY = "./web"